### PR TITLE
Simplify find function

### LINKED ISSUE #1: Redundant complexity of find function
Is there any reason to write `find()` function in this way?
```
const result = [];
const docs = text.match(GOOGLE_DOCS_REGEXP);
result.push(...docs);
return result;
```
I've tested this function with some different cases and I didn't find any reason to write this function in this way. It can be done much easier:
```
const result = text.match(GOOGLE_DOCS_REGEXP);
return result;
```

### PR DESCRIPTION
**Pull request by elszczepano**
The problem is described in #1. Closes #1.

### CODE REVIEW

**Comment by piecioshka** [comment]
I just resolve #3 and merge #4. Can you update your branch and push?

**Comment by elszczepano** [comment]
Branch updated. I've also fixed the case when there's no result.

**Comment by elszczepano** [comment]
@piecioshka can you accept the pull request and merge it? Are there any other issues related to my PR to resolve?

**Comment by piecioshka** [comment]
@elszczepano Maybe you can reduce create `result` variable by returning previous line?

**Comment by elszczepano** [comment]
@piecioshka done. 👍

**Comment by piecioshka** [comment]
Thanks @elszczepano

**Pull request merged**
